site_name: oms运维管理系统
site_description: '运维自动化 python salt django zabbix oms'
site_url: 'https://itimor.github.io/django-oms/'

repo_name: 'GitHub'
repo_url: 'https://github.com/itimor/django-oms'

theme:
  name: null
  custom_dir: themes/cinder
  show_edit: false
  logo: 'assets/images/favicon.ico'
  feature:
    tabs: true

copyright: "Copyright @ Itimor"

use_directory_urls: true

markdown_extensions:
    - admonition
    - toc:
        permalink: (ง •̀_•́)ง
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist
    - pymdownx.tilde

pages:
  - Home: index.md
  - Oms: 
    - 开始: oms/index.md
    - 基础模块: oms/base.md
    - salt与主机: oms/host.md
    - dns和zabbix: oms/dns.md
    - 办公系统: oms/oa.md
  - Problem:
    - about: problem/index.md
    - me: problem/me.md

dev_addr: 0.0.0.0:5000

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/extra.js