site_name: oms运维管理系统
site_description: 'oms运维管理系统 python salt django zabbox oms'
site_url: 'https://itimor.github.io/ojbk-oms/'

repo_name: 'Github'
repo_url: 'https://github.com/itimor/ojbk-oms'

theme:
  name: cinder
  custom_dir: themes/cinder
  language: zh
  palette:
    primary: cyan
    accent: purple
  font:
    text: Hind Siliguri
    code: Noto Sans
  logo: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/itimor'
    - type: 'twitter'
      link: 'https://twitter.com/itimor'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/itimor'
  search:
    language: 'en, zh'

copyright: "Copyright @ Itimor"

use_directory_urls: true

markdown_extensions:
    - admonition
#    - codehilite:
#        guess_lang: false
#        linenums: false
    - toc:
        permalink: (ง •̀_•́)ง
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist
    - pymdownx.tilde

pages:
  - Home: index.md
  - About: about.md